[build]
  publish = "public"
  functions = "functions"

[build.environment]
  HUGO_VERSION = "0.81.0"
  NODE_VERSION = "15.5.1"
  NPM_VERSION = "7.3.0"

[context.production]
  command = "bash synchronize.sh && cd themes/doks/ && npm i && rm -rf content/docs && cd ../.. && hugo -b $URL"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --gc --minify"
